name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ruby: [ 2.6, 2.5, 2.4, head ]
        os: [ ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Install packages
      run: |
        sudo apt update -qy
        sudo apt install libdb-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake
