name: ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.6, 2.5, 2.4, head ]
    steps:
    - uses: actions/checkout@master
    - name: Install packages
      run: |
        sudo apt update -qy
        sudo apt install libdb-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: gem install bundler --no-document
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake
